version: '3.7'

networks:
  inari:
    name: inari-network

volumes:
  mongodb-data:
    name: inari-mongodb-data
  mongodb-config:
    name: inari-mongodb-config

services:
  mongo:
    image: mongo:latest
    container_name: inari-mongodb
    hostname: mongodb
    restart: always
    volumes:
     - mongodb-data:/data/db
     - mongodb-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT:-27017}:27017