version: '3.7'

networks:
  phonk-bot:
    name: inari-network

volumes:
  mongodb-data:
  mongodb-config:
  app-db-data-inari:
    name: app-db-data-inari

services:
  db:
    image: postgres
    container_name: inari-postgres
    hostname: postgres
    restart: always
    networks:
      - phonk-bot
    volumes:
     - app-db-data-inari:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
  mongo:
    image: mongo:latest
    container_name: inari-mongodb
    hostname: mongodb
    restart: always
    volumes:
     - mongodb-data:/data/db
     - mongodb-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT:-27017}:27017