export const animeSeries = [
  {
    name: 'Kishuku Gakkou-hen',
    link: 'https://myanimelist.net/anime/55855/Kuroshitsuji__Kishuku_Gakkou-hen',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1505/141820.jpg',
    isOngoing: true,
  },
  {
    name: 'Wind Breaker',
    link: 'https://myanimelist.net/anime/54900/Wind_Breaker',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1438/141816.jpg',
    isOngoing: true,
  },
  {
    name: 'Hananoi-kun to Koi no Yamai',
    link: 'https://myanimelist.net/anime/55597/Hananoi-kun_to_Koi_no_Yamai',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1646/141411.jpg',
    isOngoing: true,
  },
  {
    name: 'Jiisan Baasan Wakagaeru',
    link: 'https://myanimelist.net/anime/56230/Jiisan_Baasan_Wakagaeru',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1676/141714.jpg',
    isOngoing: true,
  },
  {
    name: 'Merchant Meets the Wise Wolf',
    link: 'https://myanimelist.net/anime/51122/Ookami_to_Koushinryou__Merchant_Meets_the_Wise_Wolf',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1792/136743.jpg',
    isOngoing: true,
  },
  {
    name: 'Karasu wa Aruji wo Erabanai',
    link: 'https://myanimelist.net/anime/56980/Karasu_wa_Aruji_wo_Erabanai',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1630/141499.jpg',
    isOngoing: true,
  },
  {
    name: 'Bartender Kami no Glass',
    link: 'https://myanimelist.net/anime/53407/Bartender__Kami_no_Glass',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1154/141872.jpg',
    isOngoing: true,
  },
  {
    name: 'Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga Dou Medereba Ii',
    link: 'https://myanimelist.net/anime/53434/Maou_no_Ore_ga_Dorei_Elf_wo_Yome_ni_Shitanda_ga_Dou_Medereba_Ii',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1346/141203.jpg',
    isOngoing: true,
  },
  {
    name: 'Tensei shitara Dainana Ouji Dattanode Kimama ni Majutsu wo Kiwamemasu',
    link: 'https://myanimelist.net/anime/53516/Tensei_shitara_Dainana_Ouji_Datta_node_Kimama_ni_Majutsu_wo_Kiwamemasu',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1580/141243.jpg',
    isOngoing: true,
  },
  {
    name: 'Kimetsu no Yaiba Hashira Geiko-hen',
    link: 'https://myanimelist.net/anime/55701/Kimetsu_no_Yaiba__Hashira_Geiko-hen',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1136/141893.jpg',
    isOngoing: true,
  },
  {
    name: 'Kuramerukagari',
    link: 'https://myanimelist.net/anime/57478/Kuramerukagari',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1764/141678.jpg',
    isOngoing: true,
  },
  {
    name: 'Mahouka Koukou no Rettousei 3rd Season',
    link: 'https://myanimelist.net/anime/50713/Mahouka_Koukou_no_Rettousei_3rd_Season',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1040/140744.jpg',
    isOngoing: true,
  },
  {
    name: 'Maou Gakuin no Futekigousha Shijou Saikyou no Maou no Shisо Tensei shite Shison-tachi no Gakkou e Kayou II Part 2',
    link: 'https://myanimelist.net/anime/48418/Maou_Gakuin_no_Futekigousha__Shijou_Saikyou_no_Maou_no_Shiso_Tensei_shite_Shison-tachi_no_Gakkou_e_Kayou_II_Part_2',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1399/141651.jpg',
    isOngoing: true,
  },
  {
    name: 'Date A Live V',
    link: 'https://myanimelist.net/anime/52196/Date_A_Live_V',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1659/141438.jpg',
    isOngoing: true,
  },
  {
    name: 'Astro Note',
    link: 'https://myanimelist.net/anime/57391/Astro_Note',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1372/141859.jpg',
    isOngoing: true,
  },
  {
    name: 'The new Gate',
    link: 'https://myanimelist.net/anime/57100/The_New_Gate',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1898/141857.jpg',
    isOngoing: true,
  },
  {
    name: 'Vampire Dormitory',
    link: 'https://myanimelist.net/manga/121151/Vampire_Dormitory',
    posterUrl: 'https://cdn.myanimelist.net/images/manga/2/220675.jpg',
    isOngoing: true,
  },
  {
    name: 'Blue Archive',
    link: 'https://myanimelist.net/anime/54309/Blue_Archive_the_Animation',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1739/140995.jpg',
    isOngoing: true,
  },
  {
    name: 'Sand Land',
    link: 'https://myanimelist.net/anime/53882/Sand_Land',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1834/136339.jpg',
    isOngoing: false,
  },
  {
    name: 'Heike Monogatari',
    link: 'https://myanimelist.net/anime/49738/Heike_Monogatari',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1282/119979.jpg',
    isOngoing: false,
  },
  {
    name: 'Ou Dorobou Jing',
    link: 'https://myanimelist.net/anime/107/Ou_Dorobou_Jing',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1961/92115.jpg',
    isOngoing: false,
  },
  {
    name: '86',
    link: 'https://myanimelist.net/anime/41457/86',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1987/117507.jpg',
    isOngoing: false,
  },
  {
    name: 'Tomodachi Game',
    link: 'https://myanimelist.net/anime/50273/Tomodachi_Game',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1247/121345.jpg',
    isOngoing: false,
  },
  {
    name: 'Yakusoku no Neverland',
    link: 'https://myanimelist.net/anime/37779/Yakusoku_no_Neverland',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1830/118780.jpg',
    isOngoing: false,
  },
  {
    name: 'Karin',
    link: 'https://myanimelist.net/anime/469/Karin?q=karin&cat=anime',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/9/79205.jpg',
    isOngoing: false,
  },
  {
    name: 'Bonus ga Aishita Subete no Kimi e',
    link: 'https://myanimelist.net/anime/49834/Boku_ga_Aishita_Subete_no_Kimi_e',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1145/127594.jpg',
    isOngoing: false,
  },
  {
    name: 'Kimi wo Aishita Hitori no Boku e',
    link: 'https://myanimelist.net/anime/49835/Kimi_wo_Aishita_Hitori_no_Boku_e',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1332/127596.jpg',
    isOngoing: false,
  },
  {
    name: 'Another',
    link: 'https://myanimelist.net/anime/11111/Another',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/4/75509.jpg',
    isOngoing: false,
  },
  {
    name: 'Hikyou Tanken Fam Ihrlie',
    link: 'https://myanimelist.net/anime/1181/Hikyou_Tanken_Fam___Ihrlie',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1775/92278.jpg',
    isOngoing: false,
  },
  {
    name: 'Taiho Shichau zo',
    link: 'https://myanimelist.net/anime/1577/Taiho_Shichau_zo',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/1498/97153.jpg',
    isOngoing: false,
  },
  {
    name: 'Cowboy Bebop',
    link: 'https://myanimelist.net/anime/1/Cowboy_Bebop',
    posterUrl: 'https://cdn.myanimelist.net/images/anime/4/19644.jpg',
    isOngoing: false,
  },
];
